version: "3.9"
services:
  redis:
    image: "redislabs/redismod:edge"
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    entrypoint: >
      redis-server
        --loadmodule /usr/lib/redis/modules/redisgraph.so
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
